### ISSUE TITLE
Add monochrome icon

### ISSUE THREAD

**Issue by xmha97** [meshenger-app/meshenger-android#101]
Please support the Android 13 "Themed App Icons" feature.

![Screenshot_2023-04-10-03-33-53-572_de mm20 launcher2 release](https://user-images.githubusercontent.com/23485114/230802776-eb833bcd-ae19-44bc-8e12-e7a2d822f97b.jpg)

Thanks. 🙏

**Comment by mwarning** [comment]
I will have a look.

**Comment by xmha97** [comment]
> Will be fixed in the next release (4.1.6).

Thanks. 🙏

**Comment by iddq** [comment]
what is this feature exactly?

**Comment by mwarning** [comment]
@iddq it is about the Meshenger App icon to be displayed in the color tint of the other apps.
