### ISSUE TITLE
Video call is not clear

### ISSUE THREAD

**Issue by changkai244** [meshenger-app/meshenger-android#102]
When I tested video calls on a low-performance device, the video quality was blurry for the first 20 seconds of each call, but improved after 20 seconds. I set the resolution to 640*480. What other reasons may affect the video quality? Thank you very much.

**Comment by mwarning** [comment]
WebRTC probably adapts the resolution dynamically depending on the bandwidth. So far I have not tried to mke the resolution fixed.

**Comment by mwarning** [comment]
This will be fixed in the next relaease.

**Comment by mwarning** [comment]
@changkai244 please try the latest release (4.1.7)

**Comment by mwarning** [comment]
In 4.1.8 there is an option to disable CPU overuse detection. This will help you to have a better resolution as WebRTC likes to reduce the quality when CPU use is "too" high.
