### ISSUE TITLE
App keeps showing other contact as "offline" even though app is running on other device and in local network

### ISSUE THREAD

**Issue by Chewie9999** [meshenger-app/meshenger-android#105]
We have v4.1.6 installed on 2 devices, one Samsung A70, and one Fairphone 3 (Android 10).
It kind of works, but a lot of the time each others' device is showing with an orange/red dot which says it's offline (app is not running).
Could this be related to #70 and the overlay permission mentioned?
I have checked in my permissions list for the app, and it only mentions Storage, Camera and Microphone, and "No permissions denied".

**Comment by mwarning** [comment]
The contact status is updated every time the MainActivity is restarted. Maybe it would be a good idea to show a short message and allow users to send pings explicity.

**Comment by mwarning** [comment]
Every time the status is updated, a notification is show.
Also, an explicit update for a single contact can be triggrered via the context menu.

https://github.com/meshenger-app/meshenger-android/commit/bd7fac9d82a418ef2f7b4f7b8e98176fc3df5363

Closing this ticket for now.
