### ISSUE TITLE
Is there a plan to support internet communication based on ipv6？

### ISSUE THREAD

**Issue by session011** [meshenger-app/meshenger-android#106]
I am glad to see a peer-to-peer encrypted communication software that is not limited by servers, but sometimes we lack the motivation to build a remote local area network. Therefore, I would like to ask if there are plans to enable this software to support real peer-to-peer communication on the basis of the ipv6 internet.
For a totalitarian government, controlling servers is very simple, so a software that does not rely on servers is a good thing for us. We don't need to prepare a node or boot server that can be easily banned, but instead use the ipv6 address that everyone has for communication, which undoubtedly greatly facilitates communication between humans.
If the final software can support ipv6 based communication under normal network conditions, which means it has the ability to break through firewalls or NATs, then such software will have a very unique advantage compared to other software that requires servers.
And for us users, it will be easier, that's for sure. God bless you.
I am looking forward to receiving your reply, it doesn't matter whether it is yes or no.

**Comment by mwarning** [comment]
Communicating over the Internet through NAT requires a third party (usually a server) to facilitate a connection. As such, Meshenger will never support this.

The only thing that lets you communicate over the Internet with Meshenger is when both sides have a public IP address with no firewall that prevents direct communication. I tried that and was able to make calls over the Internet, but that is a rare circumstance.

**Comment by session011** [comment]
> 

I'm sorry to bother you with your time. My knowledge is so shallow. In fact, I am just a fan of encryption software. Part of what I have learned (right or wrong) is that NAT is for IPV4, while IPV6 does not have NAT. Can I use SDP to let the firewall pass？
In some regulated areas, encryption software is an important tool for safeguarding human rights.That's why I like encryption software.

**Comment by session011** [comment]
> 通过 NAT 在互联网上进行通信需要第三方（通常是服务器）来促进连接。因此，梅辛格绝不会支持这一点。
> 
> 唯一可以让您通过互联网与Meshenger进行通信的是，当双方都有一个公共IP地址，没有防火墙阻止直接通信时。我尝试过，并且能够通过互联网拨打电话，但这种情况很少见。

I'm sorry to bother you with your time. My knowledge is so shallow. In fact, I am just a fan of encryption software. Part of what I have learned (right or wrong) is that NAT is for IPV4, while IPV6 does not have NAT. Can I use SDP to let the firewall pass？
In some regulated areas, encryption software is an important tool for safeguarding human rights.That's why I like encryption software.

**Comment by session011** [comment]
@mwarning Please allow me to disturb you for the last time

**Comment by mwarning** [comment]
Hi,

IPv6 does not use NAT (there is IPv6 NAT, but it is rare). But instead you almost always have a firewall that prevents incoming connections.

As for SDP, I assume that you mean Software Defined Perimeter? From what I've read, it works by means of a authentication servide. This would probaly not be compatible with the core idea of Meshenger.

**Comment by session011** [comment]
> Hi,
> 
> IPv6 does not use NAT (there is IPv6 NAT, but it is rare). But instead you almost always have a firewall that prevents incoming connections.
> 
> As for SDP, I assume that you mean Software Defined Perimeter? From what I've read, it works by means of a authentication servide. This would probaly not be compatible with the core idea of Meshenger.

@mwarning  Thank you very much, sir. It was my carelessness in considering Meshenger's mechanism.

Because I think so, since we already know the other party's IP address, in some cases, we should be able to understand it as communication between friends, so for both communication parties, it should be possible to trust each other.

Perhaps adding friends and their public keys can block untrusted calls.

Wishing you a pleasant life, sir.

**Comment by session011** [comment]
@mwarning SDP is Session Description Protocal.
