### ISSUE TITLE
Doesn't ask for mic permission if push to talk enabled (silently fails instead)

### ISSUE THREAD

**Issue by opusforlife2** [meshenger-app/meshenger-android#108]
If the app data is cleared and push to talk is enabled, then during calls, the mic button doesn't work, because it doesn't have the mic permission. Tapping it shows the enabled green border indicator, but that's it. The app doesn't ask for the permission at any point.

**Comment by mwarning** [comment]
Is that for version 4.1.7?

**Comment by mwarning** [comment]
I was able to reproduce the problem. It might be fixed already.

**Comment by mwarning** [comment]
Shuld be fixed in 4.1.8.
