### ISSUE TITLE
Bluetooth permission: error toast spam

### ISSUE THREAD

**Issue by opusforlife2** [meshenger-app/meshenger-android#109]
By default, the app seems to be set to detect Bluetooth devices. This leads to it asking for permission to detect nearby devices when you initiate the first call. But if you deny that permission, the app simply starts spamming you with the related error toast.

Why is this permission needed? The toggle with the Bluetooth symbol on it seems to just switch between loudspeaker, earpiece, and auto, which is dependent on the proximity sensor and not Bluetooth, from what I understand.

**Comment by mwarning** [comment]
Hm, this would need a separate audio state for bluetooth, so it is not included in the automatic mode.

**Comment by mwarning** [comment]
Sorry, that is some internal state. I was writing to myself more or less. :-)

**Comment by mwarning** [comment]
The Auto setting for the loudspeaker is also dependable on Bluetooth, as it is meant to switch to Bluetooth automatically. But that needs Bluetooth permissions in the first place to check if a Bluetooth device is connected. That's why the permission is asked.

**Comment by mwarning** [comment]
But if the user changes the decision during the call, then the call would need to be restarted.

**Comment by mwarning** [comment]
> That's normal app behaviour, though? Apps usually deny that functionality until the user grants the relevant permission and then restarts the app.

I do not know. But that is definetely a way to handle it.

> Bluetooth device detection could be separated out into its own toggle in settings. And trying to toggle it on would re-request the permission. I think that's what you're concerned about? Because the user could always just go to the App Info settings and grant the permission, though that might be considered a 'power user' method.

To add a separate blutooth icon would also be a good solution.
Let's see if I can implement both.

**Comment by mwarning** [comment]
The Bluetooth spam has been reduced now in 4.1.8 (at least I hope).
