### ISSUE TITLE
Implementing custom audio compression codec

### ISSUE THREAD

**Issue by chungwinnnnnn** [meshenger-app/meshenger-android#112]
Hey there, this project seems to work amazing. I am looking to integrate a custom realtime audio compression algorithm in the form of an android compatible library into this application, but I don't have much experience in android app development, java, kotlin or webRTC. I was wondering if you would be able to provide some pointers as to how this can possibly be achieved?

**Comment by mwarning** [comment]
I do not have insights about how to add a new audio codec to WebRTC. Sorry and good luck.

**Comment by chungwinnnnnn** [comment]
No worries thank you!
