### ISSUE TITLE
Call via personal hotspot?

### ISSUE THREAD

**Issue by jrave9000** [meshenger-app/meshenger-android#114]
Is it possible? I see a couple of closed issues and a mention in the FAQ, but it is unclear if it works, and if it does, how to set it up correctly.

Currently, the caller sees "Connected" (and continues to see it while nothing works) and the other person gets an Error when trying to pick up. Everything works perfectly over normal WiFi.

**Comment by mwarning** [comment]
There are problems with using a personal hotspot. It does not work right now and I suspect some kind of firewall. But I haven't spend a lot of debugging yet.

**Comment by mwarning** [comment]
The intial connection is TCP/IP, which works. But then the WebRTC (Audio/Video) connection is using UDP.

**Comment by jrave9000** [comment]
Thanks. It's sad, because I can't find ANY alternatives to your app. I guess there could be some workarounds with the third phone or a vpn over the tethered connection.

**Comment by mwarning** [comment]
I would like there to be alternative apps. That is why I wrote this one. :-)
But anyway, it should work if you use a third phone to create a hotspot and then let two other phones connect.

**Comment by iddq** [comment]
4.3.2 is ok. Both devices can successfully establish a connection and make calls regardless of which device initiates the call.
