### ISSUE TITLE
Add possibility to edit adresses of contacts

### ISSUE THREAD

**Issue by damadmai** [meshenger-app/meshenger-android#119]
Could you please add a context menu entry (like `delete`, `rename`) which is called edit an opens a dialog like `Adress Management` which allows to edit the list of adresses of a contact.
Instead of deactivating or activating an adress it should open a text input window for the adress.

Thank you for keep improving this app!

**Comment by mwarning** [comment]
hi @damadmai,

I fully agree. The translations need more context.

> Instead of deactivating or activating an adress it should open a text input window for the adress.

Can you provide more details on how you imagine the UI? I am not a UI person. :D

**Comment by damadmai** [comment]
Ichh stelle mir das genau so wie die Liste vor unter "Address Management".
Nur dass es keine grüne und rote Färbung gibt.
Stattdessen soll das Array an Adressen in dem JSON vom Kontakt als so eine Liste angezeigt werden.
Jeder Eintrag soll auf der rechten Seite ein rotes X haben, um ihn zu entfernen.
Unten soll genauso wie "Custom Adress" ein Textfeld sein, um eine neue Adresse mit Button ADD daneben hinzuzufügen.
Ganz unten Save und Reset kann auch genauso sein.
Wenn auf einen Eintrag getippt wird, soll ein Dialog aufgehen, der ein Textfeld enthält, wo der aktuelle Eintrag bearbeitet werden kann, genau so wie der "Paste Contact Data here" Dialog.

**Comment by mwarning** [comment]
@damadmai das klingt ganz gut. Aber gerade hätte ich keine Energie das zu ändern. MRs sind natürlich willkommen.

**Comment by mwarning** [comment]
btw. the translation ids have been cleaned up now: https://github.com/meshenger-app/meshenger-android/commit/9bd75e9ef5798d2a50ef13a8ca7b878fec178ac5

**Comment by mwarning** [comment]
Anyway, I started working on this.

**Comment by mwarning** [comment]
Implemented. Will be in 4.2.2.
