### ISSUE TITLE
Android Mesh Lib / WiFi Direct / LocalOnlyHotspot

### ISSUE THREAD

**Issue by mikedawson** [meshenger-app/meshenger-android#120]
Hi,

I saw this mentioned in the FAQ:

"Simply put, this does not work reliably. It is probably an Android internal issue. The initial TCP/IP connection works, but then UDP packets for audio/video cannot cross."

https://github.com/meshenger-app/meshenger-android/blob/master/docs/faq.md

I recently completed an initial version of a WiFi mesh networking library for Android that supports TCP and UDP based on LocalOnlyHotpsot and WiFi direct groups ( https://www.github.com/UstadMobile/Meshrabiya ). It is an Android library that I have built initially for education use cases in areas without WiFi infrastructure, but built in a way that it should be possible to use within any other app.

I was able to get UDP packets to traverse the network successfully. One issue was that it was necessary to bind the DatagramSocket to the Network object received through ConnectivityManager when using a connection without Internet access (especially when it was created on Android 10+ using a NetworkSpecifier). Interestingly I found that TCP connections on Android 10 and earlier can take a very long time to connect (20 seconds) when connecting from the hotspot creator to a device on that hotspot, but this delay does not impact UDP traffic.

I would very much welcome feedback and any feature / API requests that you might need in order for this to be useful within Meshenger. Each node is given a 'virtual' IP address and the library provides socket factories for UDP and TCP. Using those socket factories data can be sent/received over multiple hops.

If you use it the name might even make more sense :)

**Comment by mwarning** [comment]
Hi there, I already noticed Meshrabiya. It is an interesting project. but I haven't had a deeper look yet.
As for Meshenger. It uses WebRTC which also creates the socket. We have no control there. :/

Meshenger itself does no meshing (despite its name) and it is not planned as a feature. But feel free to fork and combine it with Meshrabiya. :-)

**Comment by mwarning** [comment]
@mikedawson in case Meshrabiya offers a local tunnel interface I suggest to have a stable IPv6 address. Meshenger calls IP addresses, and if that address changes, then a contact won't be reachable anymore.

**Comment by mikedawson** [comment]
Thanks! I already noticed the point in the FAQ about Meshenger not itself being a mesh app.

I took a quick look: it seems like there is some initial communication over TCP first, then things get handed over to WebRTC. 

Meshrabiya by default uses a persistent IPv4 address on the 169.254/16 range, but this is being updated so that it can handle IPv6  (or even v8). It is designed to keep addresses : e.g. even if the routing changes due to nodes on the mesh dropping out etc, each node still keeps the same address. Saving an IP address as a contact should work well with that approach.

I think the best thing to do is to first add the VPN service (which would provide a tunnel interface) to Meshrabiya. Then it should be possible to run Meshenger calls over that.

If that works and it is desired to integrate within the Meshenger app to avoid the requirement for a separate tunnel/VPN app, then we'll cross that bridge when we come to it.

**Comment by mikedawson** [comment]
Thanks! What I have found with offline local networks is that it helps to use the network.bind functions (e.g. on the socket, if all else fails, bind the process to the network) to ensure that Android sees that an offline wifi network that doesn't provide Internet access is actually in use. Otherwise various Android versions have an annoying habit of disconnecting from any WiFi that doesn't provide Internet access at will (especially if mobile data is active). 

That shouldn't be a problem if/when using a Meshrabiya tunnel (because it will do those things), but might help makes things that much more reliable using access points without Internet ('normal' ones or those created by other Android devices) if they haven't been put in already.

Getting a WiFi lock also helped performance. Not sure if these are already implemented in Meshenger.

**Comment by mwarning** [comment]
@mikedawson I have tried Meshrabiya with two phones and I was able to send a file. That works! :-)
But it seems that any application that wants to use it needs to implement the custom classes of Meshrabiya.
Would you consider to make Meshrabiya also offer a tunnel interface? That would other apps to use it without changing their source code (like Meshenger).

**Comment by mikedawson** [comment]
Hi @mwarning thank you for checking it out, and happy to hear it worked for you!

Yes I am planning to add a tunnel interface so that other apps can use it without having to embed Meshrabiya in their own source code. Might also work better in situations where multiple apps want to use such a network.

**Comment by mikedawson** [comment]
It will be possible to discover other devices via Bluetooth Low Energy advertising, so then they can connect without scanning the QR code. There will still be a prompt on the device that is connecting the first time it connects to a device it hasn't connect with over WiFi before.

It would be possible to add a mode where the device automatically tries to connect to any other device that is part of the same mesh if/when it looses a connection. It might even be possible to add a network id / passphrase concept so that separate meshes can exist in the same location and a user can choose which one they want to join.

I don't think using the same Wireless SSID (different channels) approach will work (e.g. like what happens at airports etc), for this to work the access points themselves need to be connected (via cable or another wireless network).

**Comment by mwarning** [comment]
@mikedawson thank you for the heads up!
@MathJud this be of interest to you

**Comment by iddq** [comment]
there is some discussion about this issue on the webrtc mailing list recently

**Comment by mwarning** [comment]
@iddq  interesting, to you have a link?

**Comment by mwarning** [comment]
@mikedawson not sure if this is of interest to you (it is also alpha quality so far). This is a patch for hostapd to allow meshing between Access Points : https://github.com/G10h4ck/lime-packages/tree/lime_curtigghio/packages/lime-curtigghio Maybe this opens the door to allow meshing with Android phones without the need to modify the Linux Kernel (only hostapd)

**Comment by mikedawson** [comment]
@mwarning  - it is definitely interesting; but we're focused on things that work on out of the box on unmodified Android devices. Modifying hostapd is definitely beyond what a 'normal' user would/could do.

**Comment by iddq** [comment]
> @iddq interesting, to you have a link?

https://groups.google.com/g/discuss-webrtc/c/pTWe0QLKNC4/m/_ulh_2NJBwAJ

**Comment by mwarning** [comment]
hm, I suspect that WebRTC needs to be recompiled and modified. This is something that I have trouble with.

**Comment by mwarning** [comment]
Fixed in 4.3.1
