### ISSUE TITLE
Bluetooth network

### ISSUE THREAD

**Issue by muvn** [meshenger-app/meshenger-android#124]
An error occurred under Bluetooth network. It rings but does not connect.

**Comment by mwarning** [comment]
Do you have logs? Or how do you reproduce this? What Android version do you use? What kind of phone? Otherwise I won't be able to figure this out

**Comment by muvn** [comment]
I want to use the Bluetooth network to use Meshenger when there is no internet outside. But an error occurred and I can only receive calls without being able to answer them.
The following error occurred when using mobile phone A to connect to the Bluetooth network shared by B.

**A**  is motorolaX40 (XT2301-5) android 13
**B**  is SAMSUNG Galaxy Tab S8 (SM-x700) android 13

![Screenshot_20230929-114952](https://github.com/meshenger-app/meshenger-android/assets/88066247/971c0edc-73f8-4738-88bb-4a9524562b67)
![Screenshot_20230929-114851](https://github.com/meshenger-app/meshenger-android/assets/88066247/2d44a65b-d2c0-4be6-8ac7-3d655f7c3712)

**Comment by mwarning** [comment]
Hi, Meshenger does not use Bluetooth for calls. Bluetooth is only used for Bluetooth headsets.

**Comment by muvn** [comment]
It's not just a simple Bluetooth connection, it's a local network shared through Bluetooth. After all, Meshenger can ring, it just has some errors.

**Comment by mwarning** [comment]
@muvn I wasn't aware that you had an IP connection over Bluetooth. :-)
This sounds very much like the problem as when a phone creates a local hotspot, see https://github.com/meshenger-app/meshenger-android/blob/master/docs/faq.md ("Why can't you call a thethered/hotspot phone as client?")

In short, I do not know why this does not work.

**Comment by muvn** [comment]
Thank you for your answer. 😃If this problem can be solved, Meshenger will have more application scenarios. Looking forward to it.😋

**Comment by iddq** [comment]
Same issue on wifi-direct.

**Comment by mwarning** [comment]
Please try again. There has been a fix in Meshenger 4.3.1 that might fix this.
Please re-open if the issue is still present.
@iddq can you also try WiFi-Direct? If it does not work, then there is something I could enable.

**Comment by iddq** [comment]
Need some time, I will test it.

**Comment by iddq** [comment]
Both devices can successfully establish a connection and make calls regardless of which device initiates the call. Bluetooth and WiFi Direct.

**Comment by iddq** [comment]
4.3.2 is ok. Both devices can successfully establish a connection and make calls regardless of which device initiates the call.

**Comment by mwarning** [comment]
I have made an offical 4.3.2 release. Let's hope nothing broke.
