### ISSUE TITLE
Quality sharpness

### ISSUE THREAD

**Issue by CWTakiku** [meshenger-app/meshenger-android#126]
How to improve clear picture quality, adjustment does not seem to work

**Comment by mwarning** [comment]
Have you tried Meshenger 4.2.4? And have you tried changing the resolution via the menu (small gear icon in the left top corner) during a call?

**Comment by CWTakiku** [comment]
Yeah, I don't know if it's my phone's camera, but I changed it to capture and cast, and it's blurry, even though I set resolution first

**Comment by mwarning** [comment]
Then it is hard to say why WebRTC cannot or won't capture a higher quality video stream.

**Comment by CWTakiku** [comment]
I switched to h264 encoding and the sharpness improved a lot, but the latency issues remained

**Comment by mwarning** [comment]
hm, where did you switch it to h264?

**Comment by CWTakiku** [comment]
I customized the encoderFactory, which uses vp8 by default, and I changed it to h264

**Comment by mwarning** [comment]
Please share you changes. Maybe it is enough to expose the vp8 and h264 setting.

**Comment by CWTakiku** [comment]
![image](https://github.com/meshenger-app/meshenger-android/assets/28865973/99b85336-91f9-4998-818d-0f79dcfef112)

**Comment by mwarning** [comment]
Nice. Have you tried to just disable VP8? https://github.com/meshenger-app/meshenger-android/blob/master/app/src/main/kotlin/d/d/meshenger/call/RTCCall.kt#L531

**Comment by CWTakiku** [comment]
Yes, it didn't work when I just set vp8 to false, I used a custom coding factory that worked, and now my picture quality and fluency have improved when I coded with h264 and reduced the frame rate, but there is a key problem that sometimes my picture gets blurry for a moment due to the webrtc strategy
![image](https://github.com/meshenger-app/meshenger-android/assets/28865973/e38084a2-05a3-4c92-83f8-7fd2748ce564)

**Comment by mwarning** [comment]
Thank you. I will give it a try.

**Comment by mwarning** [comment]
@CWTakiku can you try a fresh install of https://github.com/meshenger-app/meshenger-android/commit/48756d0e44fe56c6c797202c1dd13005b7859197 ?

**Comment by CWTakiku** [comment]
我看了你的提交记录，你好像没有设置自定义工厂，仅仅是配置了默认加速工厂，我把我的编码工厂类提供给你看看
[新建 文本文档 (8).txt](https://github.com/meshenger-app/meshenger-android/files/12911524/8.txt)

**Comment by mwarning** [comment]
@CWTakiku thank you, I will give it a try. I did not commit my custom factory, since it broke the call feature for me.

**Comment by mwarning** [comment]
I tried the code with only isSupportedH264 returning true (like in your screenshot), but now the phones cannot establish a connection.

Aside from that, the picture quality with the current master is pretty good (HD).

**Comment by CWTakiku** [comment]
What you need is that both the receiver and the sender need to set up the custom encoder to establish the connection, and how does your image quality improve

**Comment by mwarning** [comment]
hm, I had the same software on both devices. Here is the source code: https://github.com/meshenger-app/meshenger-android/tree/h264

**Comment by mwarning** [comment]
I will do an intermediate release with enabled hardware decoding by default (it wasn't working right before). Then let's do more testing.

**Comment by CWTakiku** [comment]
Ok, theoretically it's OK, but it's been proven to work on my side and has been used in my own projects

**Comment by mwarning** [comment]
Let's close this issue. It seem to be resolved. But the CPU overuse detection might still ruin the day. But it can be disabled in the setting on the users own risk.
