### ISSUE TITLE
Contact is false-offline

### ISSUE THREAD

**Issue by sandoxy** [meshenger-app/meshenger-android#132]
Hi, after a while the app shows (my only) contact as offline and then no call is possible. Energy saving on both phones is off.

**Comment by mwarning** [comment]
Please check in the address management if the IP or MAC address of your device has changed.

**Comment by sandoxy** [comment]
The calls with that contact do sometimes work. But sometimes he most time the contact is just shown as offline. But he is still connected to the same local network. The same to my direction from that contact.

**Comment by galenthurber** [comment]
Same here w 4.2.6 
Port 10001 show available on both devices

**Comment by galenthurber** [comment]
Ah my wlan0 router MAC does not match apps MAC wlan0

**Comment by galenthurber** [comment]
After readding contact seems on now, maybe app was ignoring MAC addresses and using ip#s

**Comment by mwarning** [comment]
@galenthurber Android changes the MAC address from time to time. Maybe that was the issue.
@sandoxy you can try to disable "Automatic Contact Updates" and then send pings manually (from the menu to show/scan QR codes).

**Comment by mwarning** [comment]
I can confirm a problem with the online status - working on it.

**Comment by mwarning** [comment]
The bug is fixed in release 4.2.7. But it will take a few days to show up in f-droid.

**Comment by sandoxy** [comment]
Wow, great! Sorry, I wasn't able to test your suggestion from before.

**Comment by mwarning** [comment]
@sandoxy 'glad the bug was found. :-)

**Comment by sandoxy** [comment]
I tested the new version. Now the status is correct. But the status is red or orange. There are still no calls possible. We both are on the same wifi, but both are red or orange. But it might be a different issue.

**Comment by mwarning** [comment]
@sandoxy do you refer to the scenario where one of the phone create a WLAN hotspot?

**Comment by sandoxy** [comment]
No, we are just both connected to the same wifi-network. This way it worked in the past, but just occasionally.

**Comment by mwarning** [comment]
@sandoxy that is some other bug. I will investigate.

**Comment by mwarning** [comment]
I can confirm a conenction issue. The caller says that it is connected, while the callee reports an error. I wonder if the latest webrtc update broke something.

**Comment by sandoxy** [comment]
By the way: I have similar problems with this app: https://git.jami.net/savoirfairelinux/jami-client-android
