### ISSUE TITLE
ERROR on calls with hotspot

### ISSUE THREAD

**Issue by Xamyrz** [meshenger-app/meshenger-android#133]
I was hoping that this app would work with a hotspot turned-ON on one of the phones. the call is incoming, but then it errors out. I've ran a debugger and it displays

```
reportStateChange() state=ERROR_COMMUNICATION
onStateChange() state=ERROR_COMMUNICATION
```

Is there a possibility for a fix? I'd really like to get it to work for rides on a motorbike without much extra gear other than a phone :)

**Comment by mwarning** [comment]
Hi, this is a known issue. I suspect the problem with WebRTC. But it is hard to debug. I would need to compile WebRTC myself. But this is far from trivial (there is https://github.com/threema-ch/webrtc-build-docker).

I tried to compile WebRTC myself to debug this, but then the App crashes. :/

**Comment by ElonSatoshi** [comment]
I hope there is a fix. Maybe an alternative to WebRTC could be added?

**Comment by mwarning** [comment]
I look at this issue once in a while. Compiling WebRTC is not trivial.
@ElonSatoshi something other compared to WebRTC would be a major rewrite.

**Comment by abduljabarrahmani** [comment]
Hello, thank you for your good program, you can add chat mode, i.e. text message, in this program, thank you

**Comment by ElonSatoshi** [comment]
> Hello, thank you for your good program, you can add chat mode, i.e. text message, in this program, thank you

https://briarproject.org/

**Comment by mwarning** [comment]
Related discussion: https://github.com/meshenger-app/meshenger-android/issues/120

**Comment by mwarning** [comment]
The thethering code from the webrtc ML works. :-)
But now I wonder how to bring this into WebRTC..

**Comment by mwarning** [comment]
Please try Meshenger 4.3.1. It is intended to fix the issue.

**Comment by Xamyrz** [comment]
I've just tried it there. Google pixel 8 as tether and Samsung S21 connecting. After picking up it still errors out on incoming device and outgoing states 'connected' and closes the call few seconds later. No access to pc to debug the errors

**Comment by mwarning** [comment]
hm, this is unfortunate. Then more debugging needs to be done. It is working for me. :/

**Comment by mwarning** [comment]
It may very well  dependent on the device.

**Comment by mwarning** [comment]
@Xamyrz did you use a usb dongle with your phone or did your phone create a hotspot?

**Comment by Xamyrz** [comment]
No dongles were used

**Comment by mwarning** [comment]
The attached apk seems to be the wrong version. @Xamyrz can you check if it says 4.3.1 on the "About" page?
I have attached a new apk to https://github.com/meshenger-app/meshenger-android/releases/tag/v4.3.1

**Comment by Xamyrz** [comment]
Yes, you're right on this! It works flawlessly right now! Thank you :)

**Comment by mwarning** [comment]
@Xamyrz can you also try the 4.3.2 pre release that is attached here? https://github.com/meshenger-app/meshenger-android/releases/edit/v4.3.1
Meshenger cannot be released to F-Droid with the current approach (webrtc lib in the reprosiotry). So I thought of a different solution. It works for me. But I would like to have another confirmation.

**Comment by Xamyrz** [comment]
@mwarning 4.3.2 Pre works :)

**Comment by mwarning** [comment]
@Xamyrz awesome, then enjoy the 4.3.2 release. :)

**Comment by Xamyrz** [comment]
Thank you for pushing this out! Will give it a go on a motorbike with my partner in couple days. No more loosing signal on whatsapp/cellular calls between us

**Comment by mwarning** [comment]
@Xamyrz cool, let me know how it works for you.
