### ISSUE TITLE
one's voice could not be received by the other.

### ISSUE THREAD

**Issue by xuyf1001** [meshenger-app/meshenger-android#137]
I tested it with two mobile phones, and after installing it, it was no problem to use it for the first time, but after making a call, the second time，one's voice could not be received by the other why is this?

I use meshenger of the version of 3.03，java。Could you help me troubleshoot it? Thank you!

**Comment by xuyf1001** [comment]
> I tested it with two mobile phones, and after installing it, it was no problem to use it for the first time, but after making a call, the second time，one's voice could not be received by the other why is this?
> 
> I use meshenger of the version of 3.03，java。Could you help me troubleshoot it? Thank you!

What I found was that every time I made a call, I had to delete the background process and call again, and both of us could hear each other.

**Comment by mwarning** [comment]
Interesting, but the current Meshenger release is version 4.2.7, that is far from 3.0.3. Can you test a newer version?

**Comment by xuyf1001** [comment]
> a newer version

version of 4 is coded by adding kotlin.I dont't know much about it.

**Comment by mwarning** [comment]
I cannot help much with old Meshenger versions. As far as I remember the reason might be releated to the switch between night modes. You might want to try comment out that code.

**Comment by xuyf1001** [comment]
I use the version 4.0,also has the same problem.I feel it may be webrtc's resource releaseing,which causing it.
The first time you sign in the app,call the other phone,vedio and audio is normal. If the other hangup the phone,and call again,the audio is abnormal,always one can't hear from the other.If you kill two phone's meshenger's process, vedio and audio is normal.
