### ISSUE TITLE
hostname resolution

### ISSUE THREAD

**Issue by iddq** [meshenger-app/meshenger-android#145]
cannot resolve the hostname if the peer address is a name

**Comment by mwarning** [comment]
Can you ping that hostname from an Android terminal? (there are terminal emulators for Android)

**Comment by iddq** [comment]
it's ok from shell.

**Comment by mwarning** [comment]
I was able to reproduce the problem. The problem will be fixed in the next release. Thank you for reporting!

**Comment by iddq** [comment]
Thank you. You might consider using getAllByName when multiple A and/or AAAA records are associated with a name.

**Comment by mwarning** [comment]
Yes, that is better.

**Comment by mwarning** [comment]
fixed in 4.3.0
