### ISSUE TITLE
The latest version is 4.3.2 or 4.3.3. The released version number and the app version number do not match.

### ISSUE THREAD

**Issue by jsxzhub** [meshenger-app/meshenger-android#151]
![efb1614492dfd3d13ed98e343c5131c](https://github.com/user-attachments/assets/408da71c-6fad-4fb2-87c4-dd53ac5411a4)

![1721791510180](https://github.com/user-attachments/assets/a4d94535-a0be-411d-a21c-383ad459f5c8)

**Comment by mwarning** [comment]
The version is changed after the release. The version for the 4.3.2 release matches: https://github.com/meshenger-app/meshenger-android/blob/v4.3.2/app/build.gradle#L10
