### ISSUE TITLE
Any trick to make this app work via tailscale VPN?

### ISSUE THREAD

**Issue by hoppingninja666** [meshenger-app/meshenger-android#152]
I will appreciate it. I tried setting the tailscale address as the base address. But that approach failed. The other phone rings, but call doesn't connect after the call was answered.

**Comment by mwarning** [comment]
hi,

I suspect this is the same problem as described here (for wireguard): https://github.com/meshenger-app/meshenger-android/issues/148
It is under investigation.

**Comment by mwarning** [comment]
closed in favour of #148
