### ISSUE TITLE
changing themes sometimes does not work well

### ISSUE THREAD

**Issue by qqzz131415** [meshenger-app/meshenger-android#154]
1. at the moment, the theme is Fire Red, then change to Sky blue
2. swiping right on the screen(or press the back buttton of my android phone) to exit the setting activity rather than pressing the Navigation button,the theme is still Fire Red

**Comment by mwarning** [comment]
I can confirm this. Not a big issue, but still confusing. Thank you for reporting! Let's see if it is easy to fix.

**Comment by mwarning** [comment]
Will be fixed in the next release.

**Comment by mwarning** [comment]
fixed in 4.34
