### ISSUE TITLE
The screen is mirrored left and right after switching to the rear camera

### ISSUE THREAD

**Issue by MageDelfador** [meshenger-app/meshenger-android#155]

**Comment by mwarning** [comment]
I can only see a wrong mirroring for the small preview of your own rear camera. That shouldn't be hard to fix - I hope.

**Comment by mwarning** [comment]
Found the problem. Will be fixed in the next release: https://github.com/meshenger-app/meshenger-android/commit/eb73cab7e0e5365daf44bf8e90df2ddf53645d00

**Comment by mwarning** [comment]
Fixed in 4.3.5
