### ISSUE TITLE
JCenter is shutting down

### ISSUE THREAD

**Issue by linsui** [meshenger-app/meshenger-android#158]
F-Droid build failed. https://gitlab.com/fdroid/fdroiddata/-/jobs/7534689510 JCenter will shut down soon. Please replace and update affected libs.

**Comment by mwarning** [comment]
Rather annoying :/
But thank you for the heads up.

**Comment by mwarning** [comment]
Should be resolved in 3.4.5

**Comment by linsui** [comment]
Thanks!
