### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by userkilled** [meshenger-app/meshenger-android#16]
java.lang.NullPointerException: Attempt to read from field 'd.d.meshenger.Settings d.d.meshenger.Database.settings' on a null object reference
	at d.d.meshenger.MainService$MainBinder.getSettings(MainService.java:387)
	at d.d.meshenger.MainService$MainBinder.pingContacts(MainService.java:378)
	at d.d.meshenger.ContactListActivity.onServiceConnected(ContactListActivity.java:306)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1670)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1699)
	at android.os.Handler.handleCallback(Handler.java:794)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6662)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by mwarning** [comment]
What version is that? Did you compile it yourself or is it from f-droid?

**Comment by userkilled** [comment]
![Screenshot_2019-08-30-00-42-58-980_org fdroid fdroid](https://user-images.githubusercontent.com/39238592/63978593-5b400f80-cabf-11e9-8467-58c212d32962.png)

**Comment by mwarning** [comment]
ok, f-droid version 2.1.0. :-)

Does it crash doing specific actions? For example, adding a contact. or doing a call.

**Comment by userkilled** [comment]
This only happens when minimizing the application in MIUI 10.3.

**Comment by userkilled** [comment]
I can’t call another phone, writes 'Error'

**Comment by mwarning** [comment]
ok, have the qr codes been shared both ways?

**Comment by userkilled** [comment]
Yes

**Comment by userkilled** [comment]
And they have one local area network.

**Comment by mwarning** [comment]
Can you show the configured mac address that both devices have configured and the fe80 address they have? (maybe change same values for different ones for privacy).

So far I do not know why this is happening.

**Comment by userkilled** [comment]
![Screenshot_2019-08-30-01-15-03-458_d d meshenger](https://user-images.githubusercontent.com/39238592/63980225-9f351380-cac3-11e9-9564-cb51c7fa9b24.png)
![20190830_011557](https://user-images.githubusercontent.com/39238592/63980277-c1c72c80-cac3-11e9-8fd4-49db58a64d2b.jpg)

**Comment by mwarning** [comment]
And what is the fe80* address that is shown in the "Currently Active"  drop down address box when you click on "Change Address"?

**Comment by userkilled** [comment]
![Screenshot_2019-08-30-01-31-04-802_d d meshenger](https://user-images.githubusercontent.com/39238592/63981166-a1e53800-cac6-11e9-9466-e0cf161289dc.png)
![20190830_013247](https://user-images.githubusercontent.com/39238592/63981179-add0fa00-cac6-11e9-85e8-3b53069deae7.jpg)

**Comment by userkilled** [comment]
It's?

**Comment by mwarning** [comment]
Yes, that is very helpful. Please change the selected MAC address to the one assigned to `wlan0` on both devices and exchange the qr code again both ways. Then it should work.

I wonder why the MAC address of interface `rmnet1` was chosen by the app in the first place.

**Comment by userkilled** [comment]
I chose these interfaces to hide the address, but in fact, there were macs from the manufacturer.  The problem is not in the interfaces.

**Comment by mwarning** [comment]
Meshenger cannot change the systems MAC address... That is not made clear by the interface, yet.

**Comment by userkilled** [comment]
I wanted to say that there was a MAC (wlan0).

**Comment by mwarning** [comment]
3.0.1 will probably be available later this week. It would be nice if you could test if this problem persists.

**Comment by userkilled** [comment]
Yes, I will check.

**Comment by mwarning** [comment]
I will close this one in favor of #26. It is probably the same issue.
