### ISSUE TITLE
Importing zero size file causes endless loop 

### ISSUE THREAD

**Issue by iddq** [meshenger-app/meshenger-android#162]
https://github.com/meshenger-app/meshenger-android/blob/b7da2d3bbf95b58ff257e5b66c826f0c8a916f5d/app/src/main/kotlin/d/d/meshenger/Utils.kt#L135C36-L135C106

**Comment by mwarning** [comment]
Thank you. Fixed here: https://github.com/meshenger-app/meshenger-android/commit/8c4bbc17a2654286ad7597a2aa5ebd7bf965f029
