### ISSUE TITLE
Scan the QR code from the gallery

### ISSUE THREAD

**Issue by Zig-Rust-Odin** [meshenger-app/meshenger-android#176]
Scan the QR code from the gallery.
> meshenger Currently you need to meet in person to scan the QR code.

---
---

[Reticulum](https://github.com/markqvist/Reticulum) You only need to buy a shortwave walkie-talkie for both of you and your friend to make a true P2P voice and video call within 5-5000 km.

I personally think Meshenger can develop on the Reticulum network

**Comment by mwarning** [comment]
Meshenger is meant to be network agnostic and not tied to a specific routing layer.
Same as Recticulum wants to be hardware layer agnostic.

Since Reticulum supports IP transport, Meshenger linkely already works over Reticulum.

**Comment by mwarning** [comment]
@Zig-Rust-Odin that would be a nicer convenience functionality. But actually you can exchange the contents of the QR code as text already. The QR code show/scan elements of Meshenger have buttons for that. Just copy&paste.

**Comment by mwarning** [comment]
It should not be hard to implement to scan image from the galary. I will give it a try.

**Comment by mwarning** [comment]
The image import was added. Not sure if this open the galery: https://github.com/meshenger-app/meshenger-android/blob/master/app/src/main/kotlin/d/d/meshenger/QRScanActivity.kt#L263

**Comment by mwarning** [comment]
yeah, looks like it opens the gallery. I need to evaluate how to pick from Downloads or if the permission problem is not a big issue.

**Comment by mwarning** [comment]
Implementation is done so far. Let's release it an see if it work for the people.
