### ISSUE TITLE
Overlay permission

### ISSUE THREAD

**Issue by RealVegOs** [meshenger-app/meshenger-android#178]
I can't grant overlay permession, now the app can annoy my every time I start the app. There is no way to disable this alert. It says: [Overlay] function not awailable. It hase been disabled because it would slow down your smartphone. BTW it's a tablet.

![grafik](https://github.com/user-attachments/assets/e8d95b9d-a7cf-43a9-aec3-b591f90902f7)

**Comment by mwarning** [comment]
hm, I can add a setting to disable asking for overlay permissions. But without these permission you won't be able to receive calls when the app is in the background for some time.

**Comment by RealVegOs** [comment]
Pastafaray! Please add this. Thanks much!

**Comment by mwarning** [comment]
Added to 4.4.1. But I have hidden it in the expert settings.
