### ISSUE TITLE
add changelog

### ISSUE THREAD

**Issue by leela52452** [meshenger-app/meshenger-android#19]
can you please add changelog.
what is [CHANGELOG](https://en.m.wikipedia.org/wiki/Changelog) ?

**Comment by mwarning** [comment]
Like this? https://github.com/mwarning/trigger/tree/master/metadata/android/en-US/changelogs

**Comment by mwarning** [comment]
There is also the release list that list changes: https://github.com/meshenger-app/meshenger-android/releases

**Comment by leela52452** [comment]
> There is also the release list that list changes: https://github.com/meshenger-app/meshenger-android/releases
oh.... it is part of release. hmm...
i was expecting in a separate file, helps me understand the direction and progress of project over a period of time.
something is better than nothing.

**Comment by mwarning** [comment]
The thing is that I do not like to take care of multiple changelog locations. While it would be nice, it is a headache to maintain.
