### ISSUE TITLE
make wifi-direct work

### ISSUE THREAD

**Issue by mwarning** [meshenger-app/meshenger-android#22]
It looks like wifi direct is more involved than simply connecting to some IP address.

**Comment by labregowski** [comment]
Hi.
I left some time of this week free to visit tis issue.
Do you need me to make any test?
Best

**Comment by mwarning** [comment]
Not really, I would need to research the topic. But I will barely have any time for the next two weeks. Also, my devices wifi-direct support is broken. (I need to update those phone - still running Android 7.1).
Feel free to have a look at this issue.

**Comment by labregowski** [comment]
> .... Also, my devices wifi-direct support is broken. (I need to update those phone - still running Android 7.1).
I have it working if you want to let me know what kind of tests you need me to perform for the cause :D

**Comment by mwarning** [comment]
afaik, there needs to be code written do support wifi-direct, which I haven't done yet. I need to fix the latest release, because fdroid is complaining about (https://f-droid.org/wiki/page/d.d.meshenger/lastbuild). Sorry, I do not have time this week.

**Comment by labregowski** [comment]
> Sorry, I do not have time this week.

NP. when you need me, pls let me know

**Comment by mwarning** [comment]
I do not have time to look it this and rather close this to keep stress low :D
