### ISSUE TITLE
Allow loudspeaker while on video mode!

### ISSUE THREAD

**Issue by dbdonb** [meshenger-app/meshenger-android#25]
Currently, when you are on a video call, you are forced to get the phone close to ears (while you aren't on earphones obviously) as there is no loudspeaker provision. So, the basic idea of video call fails since you are forced to hold the phone close to the ears and end up seeing the other person's ears only.

**Comment by mwarning** [comment]
Yes, this is not a good idea. But I do not know how to switch to the speakers yet. Pull request are welcome. :-)

**Comment by dbdonb** [comment]
Well, tbh, this is the only app for android which is so clean, simple & works exactly as intended. No bloatware, no registrations, no ads, etc. So firstly, I'd thank you for bringing up such an app on this platform.

Regarding the pull request, I'm quite a noob when it comes to android dev. However, I guess you could inspect code of apps which provide loudspeaker feature, and implement it here with its function. I assume that's quite possible. I'll also try to get in touch with an android dev friend of mine.

**Comment by mwarning** [comment]
Thanks. I will try a few things as well.

**Comment by mwarning** [comment]
@dakhnod do you know how to enable loudspeakers on video calls? I tried a fey things, but nothing worked.

**Comment by TjlHope** [comment]
Don't know if this helps, but the audio management in linphone-android isn't too bad (though bluetooth headset isn't always detected):     https://github.com/BelledonneCommunications/linphone-android/blob/9a7baf96855b210b0e82f38015cf074d0cbdc987/app/src/main/java/org/linphone/utils/AndroidAudioManager.java#L407

**Comment by mwarning** [comment]
Hi @TjlHope, I already tried `AudioManager::setSpeakerphoneOn(true);` but without success. Thanks for link, I will give the approach another try when I have time.

**Comment by TjlHope** [comment]
@mwarning fair enough, I'm afraid although I do a lot of Java, I've not done any android, so can't really help. I know some of the guys at work have played around with linphone internals, so will double check if they found any gotchas.

**Comment by mwarning** [comment]
The webrtc repo has a demo app that has "all" the audio features (e.g. see https://github.com/zengpeace/apprtcmobile). But it will take some time to merge the code.

**Comment by dbdonb** [comment]
Sorry for the bump, but any update guys?

**Comment by mwarning** [comment]
hi, I am in the process of refactoring the code. With some luck it will be working afterwards.

**Comment by mwarning** [comment]
Folded into https://github.com/meshenger-app/meshenger-android/issues/70
