### ISSUE TITLE
Peers unable to detect one anothers' online status after recent update

### ISSUE THREAD

**Issue by dbdonb** [meshenger-app/meshenger-android#28]
After the recent update, peers are unable to detect the online state of other peers. It keeps searching for the status. The loader keeps working, and there's no RED/GREEN state reached.

Details:
I have two peers. Peer-1 (P1) is Android 6 while Peer-2 (P2) is Android 9. Both are connected on same network. P1 & P2 both are configured to bind to their MAC addresses over the required NICs. 

What all I tried, to resolve the issue:
-Reinstalled. 
-Replaced the profiles by scanning respective QR codes again. 
-Tried binding all possible NICs on settings for both P1 & P2.

Nothing worked. Any ideas what's suddenly gone wrong, please?

**Comment by mwarning** [comment]
Do both phones have the same version of Meshenger? (2.x is not compatible with 3.x because of crypto changes)

**Comment by dbdonb** [comment]
Yes, I updated both the phones with the latest version. Both show v3.0.3.

**Comment by dbdonb** [comment]
BUMP - Update: I downloaded the apk from github this time and installed them, and things worked fine. May be the auto update from F-droid got corrupt for me.

I'm closing this issue. Thanks for the support.

**Comment by mwarning** [comment]
ok, I was already wondering what the issue could be. But I haven't tested the f-droid build yet. Will do as soon my second phone work again..
