### ISSUE TITLE
Remove online status?

### ISSUE THREAD

**Issue by mwarning** [meshenger-app/meshenger-android#29]
This is not very reliable and does network activity even when no call is in progress. So it might simplify a few things.

**Comment by ToEatFreshBabies** [comment]
Are you suggesting disabling Presence?

**Comment by mwarning** [comment]
Yes. but I think it is best to make it configurable.

**Comment by eatanimals** [comment]
Keep presence always. It prevents rude or untimely interruptions by those with social graces.

**Comment by mwarning** [comment]
I do not see under what circumstances the presence indicator adds valuable information. If you want to call someone, then call. It might work or not in case the contact does not want to be called (contact is blocked / app or phone is offline).

**Comment by Abhishekverma2002** [comment]
If you want any help regarding the same issue , consider me in.
Would love to contribute

**Comment by mwarning** [comment]
@Abhishekverma2002 contributions are welcome!
