### ISSUE TITLE
enable audio/video by default settings

### ISSUE THREAD

**Issue by mwarning** [meshenger-app/meshenger-android#31]
- enable audio by default
- enable video by default
- accept calls by default

Might be useful in some cases. (but need to keep an eye on possible misuse)

**Comment by LostSoulfly** [comment]
This would make the app perfect for leaving old devices around the house (or wall mounting them) and acting as a sort of intercom system.

**Comment by mwarning** [comment]
@BradleyShaner agreed

**Comment by mwarning** [comment]
This has been implemented by now.
