### ISSUE TITLE
error: incompatible types: CameraVideoCapturer cannot be converted to boolean

### ISSUE THREAD

**Issue by anadi198** [meshenger-app/meshenger-android#33]
https://github.com/meshenger-app/meshenger-android/blob/2e766e97ea37e21437b52109f336acc8cfb9f065/app/src/main/java/d/d/meshenger/RTCCall.java#L441
I'm getting the error mentioned in title when building from master branch from Android Studio on the above linked line.

**Comment by mwarning** [comment]
hi,

in app/build.gradle change:
```
-    implementation 'org.webrtc:google-webrtc:1.0.28513'
+    implementation 'org.webrtc:google-webrtc:1.0.24064'
```
But master in currently in flux, because video and probably other stuff needs to be fixed.

**Comment by anadi198** [comment]
That fixed the issue, thank you.
Also, should I not clone the master branch if I want to try to fix an issue?

**Comment by mwarning** [comment]
If you want to contribute back code, then:
1. fork the project on github.com
2. there, create a branch and apply your changes
3. create a merge request

**Comment by anadi198** [comment]
Okay, thank you for the help!

**Comment by mwarning** [comment]
glad I can help :)
