### ISSUE TITLE
error: cannot find symbol variable only_necessary_for_android_6_or_later

### ISSUE THREAD

**Issue by anadi198** [meshenger-app/meshenger-android#34]
https://github.com/meshenger-app/meshenger-android/blob/2e766e97ea37e21437b52109f336acc8cfb9f065/app/src/main/java/d/d/meshenger/SettingsActivity.java#L151
`R.string.only_necessary_for_android_6_or_later` is giving error, I checked and no such item was in strings.xml.

**Comment by mwarning** [comment]
just remove the entire line. I currently use the master branch for development. So things like this are to be expected.
