### ISSUE TITLE
Help for integrating webrtc to an exiting app

### ISSUE THREAD

**Issue by HumzaAli55** [meshenger-app/meshenger-android#37]
I have a chatting app which works without a central server. I want to integrate webrtc into it for audio/video calling. I see you have integrated it on your app. Can you tell me how you did it? What steps I have to follow?

I am beginner level android developer so explain me accordingly.

**Comment by mwarning** [comment]
@HumzaAli55 I am not the original author of the Meshenger App. There is a nice android example as part of the webrtc project source called apprtcmobile. Then there https://github.com/vivek1794/webrtc-android-codelab as well and might be a bit simpler.

**Comment by mwarning** [comment]
I plan to eventually implement a chat functionality. Probably use some code from DeltaChat for that.

**Comment by mwarning** [comment]
Out of curiosity, what mechanism do you use for contacts to find each other?
