### ISSUE TITLE
Can't call when connected to the same hotspot

### ISSUE THREAD

**Issue by Carrie0302** [meshenger-app/meshenger-android#38]
I'm not sure if you are still supporting this project, but I can not use it to call when connected to the same hotspot.  Also the documentation doesn't seem to have any details on what kind of systems it supports.

**Comment by mwarning** [comment]
hi, the project is on hold until I have more resources available to push it forward .
Supported are Android Systems greater version 5.0. But there are bugs with version >= 8.0. I think you ran into a bug.

**Comment by mwarning** [comment]
I assume for now that the problem is fixed. Please open a new ticket if the issue persists.
