### ISSUE TITLE
iOS app

### ISSUE THREAD

**Issue by J053Fabi0** [meshenger-app/meshenger-android#39]
Is there any plans for an iOS app.

**Comment by mwarning** [comment]
There are no plans. It would be nice. But I have no experience with iOS. Maybe someone likes to step in. The only thing I could do is to help.

**Comment by adicoder95** [comment]
I can work on the iOS app if that's a requirement.

**Comment by atulupadhyay28** [comment]
i want to create like meshenger.
can you please share your doc.?

**Comment by mwarning** [comment]
There is no real documentation. Only the very sparse: https://github.com/meshenger-app/meshenger-android/blob/master/docs/documentation.md
