### ISSUE TITLE
online status

### ISSUE THREAD

**Issue by mwarning** [meshenger-app/meshenger-android#4]
We only have online and offline status for clients. But what is behind this is not yet clear.

What we want:
- online/green: the client phone can be reached, is running meshenger and is the one we expect to be
- ?/grey: the phone can be reached, but meshenger does not run
- offline: the phone cannot be reached at all

Currently a client is displayed as online even when it does not reply with a valid message.

**Comment by mwarning** [comment]
A less bright green would also be nice. :P

**Comment by ToEatFreshBabies** [comment]
The xmpp nomenclature for this is Presence.

**Comment by mwarning** [comment]
The mutliple distinctions in contact state are already implemented. A click on the icon also displays a text.
