### ISSUE TITLE
Can't establish a manual webrtc call to this app

### ISSUE THREAD

**Issue by djsb** [meshenger-app/meshenger-android#40]
Is the app following the standard negotiation? I was trying to build a desktop client app that would be compatible with meshenger, but can't seem to establish the video/audio after the initial negotiation. Is the video / audio also encrypted with the keys?

**Comment by mwarning** [comment]
hi,

the initial webrtc description exchange is encrypted in the code of Meshenger. Both sides needs the other contacts public key for that. After that, it's standard WebRTC communication and streams.

An outgoing call starts here:
https://github.com/meshenger-app/meshenger-android/blob/master/app/src/main/java/d/d/meshenger/RTCCall.java#L136

Then a encrypted JSON string is send. It states the "action" ( "call") and transmits the "offer" generated by WebRTC. The receiving side needs to decrypt the message and feed the "offer" to it's WebRTC library.

**Comment by djsb** [comment]
Thank you so much for the extensive detail.
Would I be able to find anywhere in the code a flag/switch/method where, if disabled, would prevent encryption?

This would allow easier debug.

Again, thanks and great project.

**Comment by mwarning** [comment]
Encryption cannot be disabled, but you bypass it in the code. But it is a bit of work.

**Comment by mwarning** [comment]
@djsb do you need help?

**Comment by djsb** [comment]
Hi @mwarning : thank you so much for following-up. I was trying to have some guidance on which methods to bypass to enable a non-encrypted negotiation.

From what I understand, from the moment the negotiation is done, no encryption exists. Would I be correct, assuming that using the method that encrypts to return the original message, would make it not encrypted?

**Comment by mwarning** [comment]
@djsb  that might work.

Just return the message variable in `decryptMessage(..)` and `encryptMessage()`:
https://github.com/meshenger-app/meshenger-android/blob/master/app/src/main/java/d/d/meshenger/Crypto.java

**Comment by mwarning** [comment]
There is a `disable_crypto` variable in the source code that you can use for experimentation. But you would need to recompile the app.
A desktop app would be awesome. But since this is an old isssue, I will close it for now.
