### ISSUE TITLE
[HELP] How to enable localRenderer, i tried, but not success.

### ISSUE THREAD

**Issue by liuxue0905** [meshenger-app/meshenger-android#42]
I add `setLocalRenderer` in `RTCCall`, 
set`org.webrtc.SurfaceViewRenderer @+id/localRenderer`visibility`visible`

and try:

add blow in `RTCCall.handleMediaStream`
```java
localRenderer.init(this.sharedContext, null);
upStream.videoTracks.get(0).setEnabled(true);
upStream.videoTracks.get(0).addSink(localRenderer);
```

or

add blow in `RTCCall.createStream`
```java
VideoTrack videoTrack = getVideoTrack();
videoTrack.setEnabled(true);
upStream.addTrack(videoTrack);
videoTrack.addSink(localRenderer);
```

`localRenderer` did not show any thing.

**Comment by mwarning** [comment]
Sorry, I did not notice this ticket before.

This is the the current problem I have myself before I took an break from this project. Let me know if you fixed this (and even better, make a pull request :-) )

**Comment by mwarning** [comment]
Have a look at the current source code. I remember that the video resources need to be initialized on the GUI thread. While the other code is not allowed on the GUI thread.
