### ISSUE TITLE
Activity d.d.meshenger.CallActivity has leaked IntentReceiver org.webrtc.NetworkMonitorAutoDetect@30e1fd1

### ISSUE THREAD

**Issue by morfeo9950** [meshenger-app/meshenger-android#43]
Im gettin this error trying to connect a call to other device.

**Comment by mwarning** [comment]
hm, the app is not really in a working state, since it needs to be updated to work properly with Android >= 8.0.
Any merge request or even fork to fix this is welcome. :-)

**Comment by mwarning** [comment]
I haven't seen the problem for a while. So I hope it is fixed. Please report again if it appears. Thank you. :-)
