### ISSUE TITLE
Error Compile

### ISSUE THREAD

**Issue by gassechen** [meshenger-app/meshenger-android#44]
Hello this error found try compile de app.

/meshenger/RTCCall.java:441: error: incompatible types: CameraVideoCapturer cannot be converted to boolean
        return factory.createVideoTrack("video1", factory.createVideoSource(this.capturer));

and this

meshenger/SettingsActivity.java:151: error: cannot find symbol
                Toast.makeText(this, getResources().getString(R.string.only_necessary_for_android_6_or_later), Toast.LENGTH_SHORT).show();
                                                                      ^
  symbol:   variable only_necessary_for_android_6_or_later
  location: class string

**Comment by mwarning** [comment]
Let me have a look. I think that is already fixed on my disk.

**Comment by mwarning** [comment]
Should at least compile now. https://github.com/meshenger-app/meshenger-android/commit/74f9aa6efaf403bda8744a8f9cf598a4d4b4c391
