### ISSUE TITLE
can't build locally

### ISSUE THREAD

**Issue by cs8898** [meshenger-app/meshenger-android#46]
Steps to reproduce

1. Clone Project
2. Build Debug
3. Run on two devices
4. Call each other

App Crashes with SegFault

https://del.dog/ovettattal.txt

**Comment by mwarning** [comment]
I suspect that is because of the webrtc library update: https://github.com/meshenger-app/meshenger-android/commit/58a581ffdd853a6f08acc2996489ffc885ab4aaf#diff-39e7d8c00954e920b98e7636f0ac30b2

You are better off using the latest release. The master branch is not in a working state.

**Comment by cs8898** [comment]
v3.0.3 is working thx

only a NullPointer in Java now
https://del.dog/afupuphico.txt

but propably i can fix it my self

**Comment by mwarning** [comment]
Awesome. Consider to create a merge request if you a fix. I do not have the time to work on meshenger.

**Comment by cs8898** [comment]
Hmm Cam also not working^^

I hoped to have a quick way to establish video feeds in a LAN area...

**Comment by mwarning** [comment]
This is probably a problem with "newer" Android versions (>=8.0). That is the biggest issue right now.

**Comment by mwarning** [comment]
You can also try the f-droid build.
