### ISSUE TITLE
Microphone - audio issue

### ISSUE THREAD

**Issue by marco19551956** [meshenger-app/meshenger-android#47]
I have installed the  MESHENGER apk versions 1.0 and also version 3.03 on my Android phones (Android 8 - 9 and 10) and they work very well except one issue.

When a connection is made (audio and/or video), the first time "NO Problems", but when the connection is closed by the caller then the next call the microphone of the called one is not working anymore. The same happens in the other way. After restarting the apps it works again for one time. Is there a solution for this issue, what can I do? 

regards  Marco

**Comment by mwarning** [comment]
Well, the only thing right now is to debug and fix it yourself (and hopefully make a merge request).

**Comment by marco19551956** [comment]
Good morning mwarning,
can you explain what a merge request is?
Thanks.

**Comment by mwarning** [comment]
A Merge Request is a way to contribute code back to this project using github.com.

**Comment by mwarning** [comment]
I assume this is fixed now. Please reopen this ticket or create a new one if it is still present. Thank you.
