### ISSUE TITLE
mutlicast support

### ISSUE THREAD

**Issue by mwarning** [meshenger-app/meshenger-android#5]
See https://github.com/dakhnod/Meshenger/issues/5

**Comment by mwarning** [comment]
This would be enable communication in mesh networks over network boundaries.

**Comment by ToEatFreshBabies** [comment]
ZeroTier?

https://github.com/zerotier

**Comment by mwarning** [comment]
Meshenger should work on ZeroTier networks. But I have not tested it.

**Comment by mwarning** [comment]
Meshenger will not support multicast discovery by design.
But it works on top of Yggdrasil, which does discovery over multicast.
