### ISSUE TITLE
Not working if no wlan?

### ISSUE THREAD

**Issue by ultimatee** [meshenger-app/meshenger-android#50]
If there is no (router) wlan on 2 phones that I want to connect,
just either WiFi Direct between the 2 phones or Android Hotspot on the first and the other connected to first's hotspot,
then no audio or video is transferred. 
The phones are reachable (can start a call between them), but no audio or video stream is transferred.

So no "real" router-less walkie-talkie is possible with this app?
Is it maybe a WebRTC issue?

**Comment by mwarning** [comment]
I have seen this problems with a hotspot on one of the phones. I think because the connection does not allow IPv6 link local connections (that would work on common networks). This would need some further inspection.
Maybe there is a firewall involved.

**Comment by mwarning** [comment]
Please try again with a recent version. It might work now.
