### ISSUE TITLE
How this library deals with ICE servers?

### ISSUE THREAD

**Issue by timaschew** [meshenger-app/meshenger-android#56]
First of all, really awesome idea and work! 🙏 

I read that WebRTC is not working without ICE servers. How do you deal with that in this app? 
You don't need them, right. Especially if it should work without internet.

I wonder if something similar can be done in a web app (with JavaScript only).

**Comment by mwarning** [comment]
Hi. thank you.

You can disable ICE in WebRTC. But usually other apps are build that way that they won't give you that option, but in many cases it makes no sense.

But if both parties have no NAT or firewall that prohibits incoming connection + they you have a way to get each others IP address, then it works.

It should be possible in web app as well.

**Comment by mwarning** [comment]
Oh, and you need to add some code to send the initial handskake yourself.
