### ISSUE TITLE
Will this project be updated again or no?

### ISSUE THREAD

**Issue by 002gRTEah3mRYH** [meshenger-app/meshenger-android#57]
Hello,

Will this project be updated again or no?

**Comment by mwarning** [comment]
Very likely.
The development branch seems to work, but is buggy in some areas.
We will try to get a Student (through GSoC) to work on it and make a release.

Anyone is invided to join development as well, of course.

**Comment by mwarning** [comment]
* I am still short on time, yes. It's life.
* the PR from @vikulin looks good, but
  * it is essentially a different project (logo, name, version, different focus?)
  * I wonder if it fixes the issue that you cannot receive calls after a few minutes in the background
* @adicoder95 has started efforts to update Meshenger as part of the Google Summer of Code 2022
  * https://github.com/orgs/meshenger-app/projects/1

**Comment by vikulin** [comment]
>I wonder if it fixes the issue that you cannot receive calls after a few minutes in the background

@mwarning most probably yes, initial tests went good.

Generraly spreaking, CupLink looks like a different project already, BTW I appreciate your work. You can join to continue work on CupLink kotlin version which has been already changed a lot.

Latest release: https://github.com/RiV-chain/CupLink/releases/tag/v0.4.3.6

It focused on an existing secure transport which is true for [RiV-mesh](https://github.com/RiV-chain/RiV-mesh). Also there are a lot of encrypted transport protocols: TLS, QUIC, I2P which can be introduced in CupLink. I decided to use an existing encrypted transport layer instead of meshengers internal one. Now CupLink creates unencrypted streams only.
Again, the meshenger was a good starting point helped me a lot with initial app sceleton,
Thanks.

**Comment by mwarning** [comment]
Hey @vikulin, awesome work you do! We might use some code for the GSoC project (with attribution, of course).

The difference between Meshenger and CupLink seems to be that Meshenger targets any network were you can reach a contact via IP address or hostname, while CupLink is for RiV-mesh. @vikulin please clarify if I am wrong here.

Anyway, Meshengers own crypto is only for the initial packet/handshake (the so called signalling data), then WebRTC takes over with encrypted streams.

**Comment by vikulin** [comment]
>The difference between Meshenger and CupLink seems to be that Meshenger targets any network were you can reach a contact via IP address or hostname, while CupLink is for RiV-mesh. @vikulin please clarify if I am wrong here.

Difference between Meshenger and CupLink:
* Mashenger uses MAC address to setup communication interface, CupLink does not.
* Meshenger uses IP to setup communication interface. CupLink **does it** as well, RiV-Mesh provides only IP interface.
* Meshenger uses some internal encryption for transport, CupLink does not, it relays on existing transport encryption as I have already said.
* Meshenger encrypts user database, CupLink does not. It will migrate to SharedPreferences which provides encrypted db as well.

**Comment by mwarning** [comment]
The MAC address is shared by default in the QR-Code, since  a IP address can be dervied from that.

I wasn't aware that SharedPreferences supports encryption. But I see that EncryptedSharedPreferences is available in androidx. :-)

**Comment by vikulin** [comment]
> The MAC address is shared by default in the QR-Code, since a IP address can be dervied from that.
> 
> I wasn't aware that SharedPreferences supports encryption. But I see that EncryptedSharedPreferences is available in androidx. :-)

Right, EncryptedSharedPreferences implements SharedPreferences interface.

**Comment by opusforlife2** [comment]
Great to see the app being worked on as part of GSoC! :)

**Comment by adicoder95** [comment]
Already started you can follow the progress on GSOC-22 branch

**Comment by opusforlife2** [comment]
@adicoder95 I'm willing to test dev builds if you need a tester at some point. 👍

**Comment by adicoder95** [comment]
Sure I will let you know @opusforlife2

**Comment by adicoder95** [comment]
@opusforlife2 I completed all the stuffs so far and pushed to GSOC-22 branch.
For testing you want me to send you a debug apk?

**Comment by opusforlife2** [comment]
Posting it here or in a new "Debug Testing" issue would be fine?

**Comment by 002gRTEah3mRYH** [comment]
updated, nice
