### ISSUE TITLE
A confusing widget on "Meshenger" 's UI

### ISSUE THREAD

**Issue by b450mhdv** [meshenger-app/meshenger-android#58]
Hello @mwarning  , I enjoy using this app! But I found a small problem with the app's UI design. When I use the app for the first time, I need to enter my name. However, I want to do this after seeing the homepage. So, when I click cancel, I find that the app exits directly. I think this widget may be misleading, and just as a personal suggestion, I think the naming operations can be delayed until entering the main page, which will attract more users.
So, could you consider redesigning the widget? And thanks for your useful app!
<img src="https://user-images.githubusercontent.com/78015408/167301876-957dfaad-8901-470e-8090-f52fc5dddb4b.jpg" width="300px"/>

**Comment by mwarning** [comment]
Yes, this should be removed. A name can be set later.

**Comment by adicoder95** [comment]
Fixed that in the GSOC-22 version
