### ISSUE TITLE
Should we have an iOS app for meshenger.

### ISSUE THREAD

**Issue by adicoder95** [meshenger-app/meshenger-android#63]
I just saw a 2 years old issue asking about if we'll ever have an iOS app.
I have been learning swift for a while now and I believe I can work on the iOS app too.
So if that's a requirement then lets go for it too.

**Comment by mwarning** [comment]
Well, I have no experience on iOS, but if there is enough time left at the end, then why not :)

**Comment by adicoder95** [comment]
I have experience in iOS app so sure, let's think about it once we are done with the Android version.

**Comment by zhubinsheng** [comment]
do it by flutter for android/ios/pc

**Comment by mwarning** [comment]
whoever has flutter experience, feel free to go ahead.

**Comment by mwarning** [comment]
I will close this one. There are no resources to make this App for iOS.

**Comment by zhubinsheng** [comment]
start
