### ISSUE TITLE
Rename variables from underscore to CamelCase

### ISSUE THREAD

**Issue by mwarning** [meshenger-app/meshenger-android#75]
Kotlin (or rather Android Studio) complains about local varaibles that have underscores.
All such variables need to be renamed. E.g. "new_from" => "newFrom"

**Comment by Rarj** [comment]
hi @mwarning , it means you want to replace snake_case into CamelCase on the whole project?
can you please assign it to me? 

thanks!

**Comment by GeorgeET15** [comment]
Is this is issue still open ?

**Comment by mwarning** [comment]
yes, so far.

**Comment by mwarning** [comment]
resolved
