### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by Ygarr** [meshenger-app/meshenger-android#87]
Contact added successfully. But with Internet in same LAN all contacts are red so no call connection between them.
If connect to each other via hotspot on one of phones both contacts are yellow, but still unable make a call - attempt ends with an error

**Comment by mwarning** [comment]
This can have different causes. Most often, the WIFi MAC address (and therefore the link local fe80::* address) of the target changed. This is causes by MAC address randomization being enabled.

Go to the address setting and click on it. If it is red, then the selected address cannot be found on the system anymore.

The solution is to make the WiFi MAC address for the WiFi network (SSID) permanent. The Android setting to do this changed over the various Adndroid releases.

**Comment by mwarning** [comment]
I have added a small section here: https://github.com/meshenger-app/meshenger-android/blob/master/docs/documentation.md

But it might not be very good so far. In progress.

**Comment by mwarning** [comment]
Are both Meshenger versions different? There is a bug that prevents 4.0.4/4.0.3 to connect to.4.0.2.

**Comment by mwarning** [comment]
Closing this issue, no response.
