### ISSUE TITLE
Accessibility issues in GUIs

### ISSUE THREAD

**Issue by Kazaf123** [meshenger-app/meshenger-android#88]
**Description**
This is a bug report about components that have accessibility issues within the GUI of such an App.
Also, as the following Figure, this report focuses on the content GUI page in the App.
<img width="360" alt="MuMu20221127164324" src="https://user-images.githubusercontent.com/44084361/204126459-cc8c87c4-0858-4817-983d-b2ee79093382.png">
**Content**
After I applied my proposed tool to detect the content page, I discovered the following components which have accessibility issues, and I sincerely struggled you could repair these issues so that the visually impaired users would use this App more conveniently.
The text of "联系人" and "事件" are too small to find for low-vision users. I would appreciate it if these texts could be enlarged.

**Comment by mwarning** [comment]
Yes, that's rather small. I will try to increase the font size.

**Comment by Kazaf123** [comment]
Thanks a lot! Looking forward to the results of your adjustment.



---- Replied Message ----
| From | Moritz ***@***.***> |
| Date | 11/27/2022 23:09 |
| To | ***@***.***> |
| Cc | Mengxi ***@***.***>***@***.***> |
| Subject | Re: [meshenger-app/meshenger-android] Accessibility issues in GUIs (Issue #88) |

Yes, that's rather small. I will try to increase the font size.

**Comment by mwarning** [comment]
![Screenshot_20221127_223227](https://user-images.githubusercontent.com/546193/204160584-76912644-f3df-42fb-9f2c-e82b6b6bc8ee.png)

I hope that is better.
