### ISSUE TITLE
How does the app work?

### ISSUE THREAD

**Issue by Fidannyan** [meshenger-app/meshenger-android#90]
Does it work without Internet and SIM card?

**Comment by straw-hat-senpai** [comment]
Hi, @Fidannyan yes the app works without internet and sim card. It uses local network to establish connections. Head over to [https://github.com/meshenger-app/meshenger-android/blob/master/README.md#meshenger](url) and also read documentation for more details.

**Comment by Fidannyan** [comment]
Does it even work without Wi-Fi?

**Comment by Fidannyan** [comment]
It doesn't seem to work

**Comment by mwarning** [comment]
@Fidannyan the App works over existing WiFi networks (via your WiFi router or phone hotspot)

**Comment by Fidannyan** [comment]
You can't make calls as soon as the Wi-Fi turns off.Both devices do not have Wi-Fi turned on

**Comment by Fidannyan** [comment]
When you activate it, you can make a call.
