### ISSUE TITLE
Add autostartup option to listen for incoming calls

### ISSUE THREAD

**Issue by Repp12** [meshenger-app/meshenger-android#94]
A set and forget but still receive calls even after phone restart without manually starting app would be very handy especially for newcomers.

**Comment by mwarning** [comment]
Good idea. This feature will be implemented in the next version. :-)

**Comment by mwarning** [comment]
I have pushed the code and close this ticket already.

**Comment by iddq** [comment]
Could you please add some logging about socket operations like listen?

It doesn’t start listening after BOOT even though the process is running. It only starts listening when I bring it to the foreground for the first time.
