### ISSUE TITLE
Group video conference

### ISSUE THREAD

**Issue by Repp12** [meshenger-app/meshenger-android#95]
Does this app have this feature and if not I'd like to request this feature as WebRTC seems capable of group calls.

It would also be nice if you can add a contact while in call and automatically merge them into the current group call session like in Facebook Messenger.

**Comment by mwarning** [comment]
It's possible to do in theory, but not easy to implement.

**Comment by mwarning** [comment]
It is not planned. But if someone would implement it, that would definitely be much appreciated.

**Comment by mwarning** [comment]
Let's close this issue. It is out of the primary scope of the project.

**Comment by mwarning** [comment]
https://jami.net/ has group chats.
