### ISSUE TITLE
Proximity sensor being left on after call ends

### ISSUE THREAD

**Issue by opusforlife2** [meshenger-app/meshenger-android#96]
I'd reported this for the pre-release test versions, but for some reason I thought it was fixed. At least with versions 4.1.0 and 4.1.1, I still encounter it.

Whenever two devices are connected on a call, whichever device ends the call is the lucky one. For the other device, its proximity sensor stays on until the app is force-stopped from settings.

Pretty major bug, since this also prevents the screen timeout from working, and is a potential battery drain.

**Comment by mwarning** [comment]
I can replicate the problem, let's see.

**Comment by mwarning** [comment]
This should fix the problem: https://github.com/meshenger-app/meshenger-android/commit/767b63318dc28807f418cebeea4cd0d3f78dc13a
