### ISSUE TITLE
Ukrainian translation

### ISSUE THREAD

**Issue by odkate** [meshenger-app/meshenger-android#98]
[values-uk.zip](https://github.com/meshenger-app/meshenger-android/files/10662415/values-uk.zip)
Please add it to the next release

**Comment by mwarning** [comment]
Added here https://github.com/meshenger-app/meshenger-android/commit/9d6c59b06491025e8a4220ebceacdb6be4b49e3e
Thank you!

**Comment by mwarning** [comment]
I had to remove some of the ukrainian translations for the release (https://github.com/meshenger-app/meshenger-android/commit/881179aafa0e5387450bccebe27cfff316fbed76). For release builds this causes linter errors if the base translation (https://github.com/meshenger-app/meshenger-android/blob/master/app/src/main/res/values/) does not contain those strings.
Can you tell me how you got the origjnal list of translatable strings?

**Comment by odkate** [comment]
from the folder values

**Comment by mwarning** [comment]
weird, those values that I had to remove are not in the folder. :P

**Comment by odkate** [comment]
I unpacked the apk file, not downloaded it from github

**Comment by mwarning** [comment]
I see, thank you for the information.
