### ISSUE TITLE
PTT FUNCTION

### ISSUE THREAD

**Issue by pyopower** [meshenger-app/meshenger-android#99]
Hello. the app is simply brilliant.Adding a PTT function as a walkie or intercom would be very interesting.

**Comment by mwarning** [comment]
Yes, that would be nice to have.

**Comment by mwarning** [comment]
Implemented here: https://github.com/meshenger-app/meshenger-android/commit/0de05cf5743dabd6b3c3df621cd33887a9115d9e
(not yet tested, may need some fixups)

**Comment by pyopower** [comment]
wow,I'm looking forward to try

**Comment by pyopower** [comment]
When will it be compiled into a new version?

**Comment by mwarning** [comment]
The next release will be some time next week.

**Comment by mwarning** [comment]
The release is out. It will take a few days to appear on f-droid.
